[versions]
agp = "8.9.1"
kotlin = "2.0.0"
android-minSdk = "30"
android-compileSdk = "35"

[libraries]

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
